//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMBO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMBO()
        {
            this.CT_COMBO = new HashSet<CT_COMBO>();
        }
    
        public string MaCombo { get; set; }
        public string MaDotKM { get; set; }
        public Nullable<double> TyLeKM { get; set; }
    
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_COMBO> CT_COMBO { get; set; }
    }
}
