//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DONDATHANG
    {
        public int MaDonDatHang { get; set; }
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NgayDuyet { get; set; }
        public Nullable<int> MaNVDuyet { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string MaNVGiao { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> TinhTrangThanhToan { get; set; }
    
        public virtual HANG HANG { get; set; }
        public virtual DONDATHANG DONDATHANG { get; set; }
    }
}
