//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAPHANG
    {
        public int MaPhieuNH { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<double> GiaNhap { get; set; }
    
        public virtual HANG HANG { get; set; }
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
    }
}
