//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNHAP
    {
        public string MaNV { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> PhanQuyen { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
