//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG()
        {
            this.GIAs = new HashSet<GIA>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaLoaiHang { get; set; }
        public string DVT { get; set; }
        public string MaNCC { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIA> GIAs { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
