//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public string MaHang { get; set; }
        public System.DateTime NgayTon { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> TonCuoi { get; set; }
    
        public virtual HANG HANG { get; set; }
    }
}
